---
# tasks file for apache

- name: "Include variaveis por OS"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Instala servidor Web Apache ( OS base {{ ansible_os_family }} )"
  yum:
    name: "{{ packages }}"
    state: installed
  when: ansible_os_family == "CentOS"
  register: http_installed
  notify:
    - Start httpd

- name: "Instala servidor Web Apache (OS base {{ ansible_os_family }} )"
  when: ansible_os_family == "CentOS"
  import_tasks: install.yml

- name:  Configura o Serviço Bind (Os base {{ ansible_os_family }} )
  when: ansible_os_family == "CentOS"
  import_tasks: configure.yml
...
